config/routes.rb
Rails.application.routes.draw do

  resources :tweets
  # resources :photos
  resources :fotos , as: :photos, controller: :photos, path_names: { new: 'nuevo', edit: 'editar'}

  get "test/", to: "photos#test"

  get "about/display"

  root to: "main#hello"
  post "hi", to: "main#greetings"

  get "companies", to: "companies#show"

  get "users/show"
  # get "users", to: "users#show"
  get "usuarios", to: "users#show", as: :users

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/photo.rb
# == Schema Information
#
# Table name: photos
#
#  id         :integer          not null, primary key
#  image_url  :string
#  title      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  todo_id    :integer          not null
#
# Indexes
#
#  index_photos_on_todo_id  (todo_id)
#
# Foreign Keys
#
#  todo_id  (todo_id => todos.id)
#
class Photo < ApplicationRecord
  belongs_to :todo
  has_and_belongs_to_many :tags
  # validates :title, presence: true, uniqueness: { message: "title [%{value}] has been already used on [%{attribute}] field of model [%{model}]" }
  validates :title, presence: true, uniqueness: { message: ->(object, data) { "data= [#{data}], data=[#{data[:value]}], object: [#{object.title}]"} }
  validates :image_url, presence: true, format: { with:  /.\.(jpg|png|jpeg|gif)/ , message: "The image url: [%{value}] is on Invalid format"}
  # scope :latest, -> { order("id desc") }
  scope :latest, ->(my_limit) { order("id desc").limit(my_limit) } do
    def foo 
      puts "Hi everyone!"
    end
  end
  scope :ascendent, -> { order("id asc") }

  def self.paginate(page=1, per_page=15)
    Photo.order("id desc").offset((page - 1)* per_page).limit(per_page)
  end
end

app/models/tag.rb
# == Schema Information
#
# Table name: tags
#
#  id         :integer          not null, primary key
#  color      :string
#  title      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Tag < ApplicationRecord
  has_and_belongs_to_many :photos
end

app/models/todo.rb
# == Schema Information
#
# Table name: todos
#
#  id          :integer          not null, primary key
#  title       :string
#  description :text
#  due_date    :datetime
#  priority    :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Todo < ApplicationRecord
  has_many :photos, dependent: :destroy
  validates :title, presence: true, uniqueness: true
  validate :due_date_is_valid
  before_validation :set_title_default_if_it_is_empty

  private

    def due_date_is_valid
      if due_date < DateTime.now
        errors.add(:due_date, "Invalid due date")
      end
    end

    def set_title_default_if_it_is_empty
      self.title ||= (0...8).map { (65 + rand(26)).chr }.join
    end
end

app/models/tweet.rb
# == Schema Information
#
# Table name: tweets
#
#  id         :integer          not null, primary key
#  body       :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  username   :string
#  surname    :string
#
class Tweet < ApplicationRecord
  after_create :send_notifications

  private
    def send_notifications
      puts "Send notifications"
    end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def display

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def show
    
  end
end

app/controllers/concerns/Geolocalizable.rb
require "active_support/concern"

module Geolocalizable
  extend ActiveSupport::Concern

  included do
    # Macro of a class
    before_action :set_country_by_ip
  end

  def set_country_by_ip
    puts "Set country by ip"
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  # skip_before_action :verify_authenticity_token

  def hello
  end

  def greetings
    @name = params[:name]
    puts @name
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  include Geolocalizable
  skip_before_action :verify_authenticity_token
  before_action :set_photo , only: [:show, :update, :destroy]

  def test
    # render "test1"
    # render "/test2"
    render "/users/test3"
  end
  
  def index
    puts params[:name]
    @all = Photo.all
  end

  def show
    # Assigned on before_action :set_photo: 
    # @photo = Photo.find(params[:id]) 

    respond_to do | format |
      format.html { render :show }
      format.json { render json: @photo }
    end

  end

  def new
    session[:attempts] = session[:attempts] ? session[:attempts] +1 : 1
    # session[:attempts] = session[:attempts] + 1
  end

  def create
    # photo = Photo.new
    # photo.title = params[:photo][:title]
    # photo.image_url = params[:photo][:image_url]
    # photo.save

    # redirect_to "/photos/#{photo.id}"
    # redirect_to photo

    # respond_to do | format |
    #   format.html { redirect_to "/photos"}
    #   format.json { render json: photo }
    # end

    @photo = Photo.new(photo_filtered_params)

    respond_to do | format |
      if @photo.save
        format.html { redirect_to @photo}
        format.json { render json: @photo }
      else
        format.html { 
          redirect_back fallback_location: photos_path,  
          notice: "Error : #{@photo.errors.full_messages.to_sentence}"}
      end
    end

  end

  def edit
    @id = params[:id]
  end

  def update
    # photo = Photo.find(params[:id])
    # photo.title = params[:photo][:title]
    # photo.image_url = params[:photo][:image_url]
    # photo.save

    # Assigned on before_action :set_photo :
    # @photo = Photo.find(params[:id]) 

    @photo.update(photo_filtered_params)

    redirect_to @photo
  end

  def destroy
    # Assigned on before_action :set_photo: 
    # @photo = Photo.find(params[:id])

    @photo.destroy
    
    puts "DESTRUIIII"*200

    puts "REDIRECT TO:"
    puts photos_path
    # byebug
    redirect_to photos_url
    # respond_to do | format |
    #   format.html { redirect_to photos_path }
    #   # format.json { head 200 }
    #   # format.json { head :ok }
    #   # format.json { head :no_content }
    # end
  end

  private

  def photo_filtered_params
    params.require(:photo).permit(:title, :image_url)
  end

  def set_photo
    @photo = Photo.find(params[:id])
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: %i[ show edit update destroy ]

  # GET /tweets or /tweets.json
  def index
    @tweets = Tweet.all
  end

  # GET /tweets/1 or /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets or /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to tweet_url(@tweet), notice: "Tweet was successfully created." }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1 or /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to tweet_url(@tweet), notice: "Tweet was successfully updated." }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1 or /tweets/1.json
  def destroy
    @tweet.destroy

    respond_to do |format|
      format.html { redirect_to tweets_url, notice: "Tweet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:body, :username)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/about/display.html.erb
<p>Informations about us</p>

<p> Link to <%= link_to "Start", root_url %></p>

<p> root_path: <%= root_path %> </p>

<p> root_url: <%= root_url %> </p>

app/views/companies/show.html.erb
COMPANIES!

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Authenticator</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if notice %>
      <p><%= notice %></p>
    <% end %> %>
    <%= yield %>
  </body>
</html>

app/views/main/greetings.html.erb
Hi <%= @name %> !

app/views/main/hello.html.erb
 <%= form_tag "hi", method: :post , data: { turbo: false } do %> 
 <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <div>
    <%= label_tag :name , "Your name:", style: "margin-left:5em;" %>
    <%= text_field_tag :name %>
  </div>
  <div>
    <%= submit_tag "Send" , style: "margin-left:15em;margin-top:2em"%>
  </div>

<%end%>

app/views/photos/edit.html.erb
<form action=<%= photo_path(@id) %> method="post">
<%= hidden_field_tag :authenticity_token, form_authenticity_token %>

<input type="hidden" name="_method" value="PATCH">

  <div>
    <label for="title">Title</label>
    <input type="text" name="photo[title]" id=title>
  </div>

  <div>
    <label for="image_url">Url of the image</label>
    <input type="url" name="photo[image_url]" id=image_url>
  </div>

  <input type="submit" value="Send it">
</form>

app/views/photos/index.html.erb
Photos:

<% @all.each do |element| %>

  <p>
    ID: <%= element.id %>
  </p>

  <p>
    Title: <%= element.title %>
  </p>

  <p>
    <%= image_tag element.image_url %>
  </p>

  <p>
    <%= link_to "See more!", element %>
    <%= link_to "Edit", edit_photo_path(element) %>
    <%= link_to "Delete", photo_path(element), data: { "turbo-method": :delete , turbo_confirm: 'Are you sure?'} %>
  </p>

<%end%>

app/views/photos/new.html.erb
Attempts = <%= session[:attempts] %>
<form action=<%= photos_path %> method="post">
<%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <div>
    <label for="title">Title</label>
    <input type="text" name="photo[title]" id=title>
  </div>

  <div>
    <label for="image_url">Url of the image</label>
    <input type="url" name="photo[image_url]" id=image_url>
  </div>

  <input type="submit" value="Send it">
</form>

app/views/photos/show.html.erb
Show details
<p>
  <%= @photo.title %>
</p>

<p>
  <%= image_tag @photo.image_url %>
</p>

  <p>
    <%= link_to "Edit", edit_photo_path(@photo.id) %>
    <%= link_to "Delete", photo_path(@photo.id),  data: { "turbo-method": :delete }  %>
  </p>

app/views/photos/test1.html.erb
On test1

app/views/tweets/_form.html.erb
<%= form_with(model: tweet) do |form| %>
  <% if tweet.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
        <% tweet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

    <div>
    <%= form.label :username, style: "display: block" %>
    <%= form.text_field :username %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tweets/_tweet.html.erb
<div id="<%= dom_id tweet %>">
  <p>
    <strong>Body:</strong>
    <%= tweet.body %>

    <strong>Username:</strong>
    <%= tweet.username %>
  </p>

</div>

app/views/tweets/edit.html.erb
<h1>Editing tweet</h1>

<%= render "form", tweet: @tweet %>

<br>

<div>
  <%= link_to "Show this tweet", @tweet %> |
  <%= link_to "Back to tweets", tweets_path %>
</div>

app/views/tweets/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Tweets</h1>

<div id="tweets">
  <% @tweets.each do |tweet| %>
    <%= render tweet %>
    <p>
      <%= link_to "Show this tweet", tweet %>
    </p>
  <% end %>
</div>

<%= link_to "New tweet", new_tweet_path %>

app/views/tweets/new.html.erb
<h1>New tweet</h1>

<%= render "form", tweet: @tweet %>

<br>

<div>
  <%= link_to "Back to tweets", tweets_path %>
</div>

app/views/tweets/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @tweet %>

<div>
  <%= link_to "Edit this tweet", edit_tweet_path(@tweet) %> |
  <%= link_to "Back to tweets", tweets_path %>

  <%= button_to "Destroy this tweet", @tweet, method: :delete %>
</div>

app/views/users/show.html.erb
Users!

app/views/users/test3.html.erb
On test3